site_name: 'PAYDAY 2 Modding Documentation'
site_description: 'See title'
site_url: 'https://theokrueger-mods.gitlab.io/pd2-docs/'
repo_url: 'https://gitlab.com/theokrueger-mods/pd2-docs/'

nav:
        - 'Index': 'index.md'
        - 'Basic Lua':
                - 'Intro': 'lua/index.md'
                - 'Structure': 'lua/structure.md'
                - 'Mod Definition': 'lua/moddefinition.md'
                - 'Writing the Mod': 'lua/writingthemod.md'
        - 'Advanced Lua':
                - 'Hooks': 'lua/hooks.md'
                - 'Automatic Updates': 'lua/autoupdate.md'
        - 'Vanilla BLT':
                - 'Index': 'blt/index.md'
                - 'Utilities':
                        - 'QuickMenu': 'blt/util/quickmenu.md'
        - 'Resources':
                - 'Documentation': 'resource/docs.md'
                - 'Tools': 'resource/tools.md'
        - 'About': 'about.md'

theme:
        name: null
        custom_dir: 'theme/mkdocs_windmill'
        static_templates: [404.html]
        search_index_only: false
        include_search_page: true
